// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynwvqmoxtmmyjnoguffg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlud3ZxbW94dG1teWpub2d1ZmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjQ3MjEsImV4cCI6MjA2NzMwMDcyMX0.bRAkOPZrBNmLKQgkf9xekEmX0k97C8EuWgW5OGhnGKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});